SET TRUENULLCREATE = OFF;
CREATE TABLE "GCG_5844_API" (
 "APIKEY" LONGVARCHAR,
 "APIPASS" LONGVARCHAR,
 "SINCE_DATE" DATE,
 "SHOPIFY_VER" VARCHAR(10),
 "REC_ID" IDENTITY DEFAULT '0' CONSTRAINT "UK_RED_ID" UNIQUE USING 1,
 "LAST_PID" INTEGER,
 "LAST_RUN_TIME" DATETIME );

CREATE TABLE "GCG_5844_EMAILS" (
 "Autonum" IDENTITY DEFAULT '0' CONSTRAINT "UK_Autonum" UNIQUE USING 0,
 "EMAIL_ADDR" LONGVARCHAR,
 "RECIPIENT_NAME" CHAR(100) );
 
 CREATE TABLE "GCG_5844_INV_ASSOC" (
 "WEBID" CHAR(50),
 "INV_PART" CHAR(50) );
 
CREATE TABLE "GCG_5844_ORDERS_XREF" (
 "OrderWebID" CHAR(25),
 "Customer" CHAR(8),
 "CustExtID" CHAR(20),
 "OrderNo" CHAR(20),
 "OrderLine" CHAR(5),
 "OrdDate" DATE,
 "QtyOrdered" NUMERIC(8,4),
 "PartNo" CHAR(20),
 "Rev" CHAR(3),
 "Loc" CHAR(2),
 "LineKey" INTEGER,
 "Last_Fin_Status" CHAR(20),
 "Line_Item_ID" CHAR(25) );
SET TRUENULLCREATE = ON;

